version: '3.8'
name: dotnet-webapi-starter-kit
services:

  api:
    image: iammukeshm/dotnet-webapi-starter-kit:latest
    container_name: api
    pull_policy: always
    networks:
      - fullstackhero
    depends_on:
      - db
      - seq

  db:
    container_name: db
    image: postgres:16.1-alpine
    networks:
      - fullstackhero
    environment:
      - POSTGRES_USER=posgresqladmin
      - POSTGRES_PASSWORD=posgresqladmin
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - db-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgresqladmin"]
      interval: 10s
      timeout: 5s
      retries: 5
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
volumes:
  db-data:

networks:
  fullstackhero:
    name:  fullstackhero